# specify runtime for the nodejs apps
runtime: nodejs12

# state the instance for the deployment
instance_class: F1

# handlers for apps
handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto